//! Builds the two files bombyx writes onto the VM host: the
//! Vagrantfile and the bootstrap script.
//!
//! A Vagrantfile tells Vagrant how to build a VM. Normally a
//! project writes its own and keeps it in its repo. bombyx
//! writes it instead, because Vagrant has to read that file
//! *before* the VM exists, so it cannot come from inside the
//! VM -- and outside the VM is where we are trying not to put
//! the project's files. `docs/trust-boundary.md` explains why.
//!
//! The split between the two files is worth understanding.
//!
//! The Vagrantfile changes per project -- different box,
//! different memory -- so it is built here, with config values
//! pasted into it.
//!
//! [`BOOTSTRAP`] is the same for every project, always. It is
//! shipped exactly as written, and bombyx pastes nothing into
//! it. Anything it needs to know arrives as an environment
//! variable that Vagrant sets. That is the point: pasting
//! config values into a shell script is where quoting bugs and
//! injection holes come from, so we simply never do it.

use crate::config::Config;

/// The provisioning script, shipped to the host unchanged.
///
/// Held as a file rather than a string literal so it is
/// syntax-highlighted, `shellcheck`-able and diffable.
pub const BOOTSTRAP: &str = include_str!("../templates/bootstrap.sh");

/// The Vagrantfile's name on the VM host.
pub const VAGRANTFILE_NAME: &str = "Vagrantfile";

/// The bootstrap script's name on the VM host.
///
/// The Vagrantfile's `path:` is relative to the directory the
/// Vagrantfile is in, so the two names have to agree and are
/// stated once here.
pub const BOOTSTRAP_NAME: &str = "bootstrap.sh";

/// Wraps `value` in double quotes, ready to drop into Ruby.
///
/// Three characters would otherwise change what the Ruby means
/// rather than appearing in it:
///
/// - `"` would end the string early.
/// - `\` would start an escape sequence.
/// - `#` starts Ruby's `#{...}`, which runs code and pastes the
///   result in.
///
/// Each gets a `\` in front of it, which tells Ruby to treat it
/// as an ordinary character.
///
/// We escape *every* `#`, not only the ones followed by `{`.
/// `\#` is just `#` to Ruby, so escaping the harmless ones costs
/// nothing -- and a rule with no exceptions cannot be got around
/// by some spelling nobody thought of.
///
/// You may notice the config checks already refuse all three of
/// these, which makes this look redundant. It is not. Those
/// checks only run when the value came from `bombyx.toml`, and
/// `Config`'s fields are public, so code using bombyx as a
/// library can build one by hand and call straight in here. A
/// function should not need a check in a different file to be
/// correct.
fn ruby_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for c in value.chars() {
        if matches!(c, '"' | '\\' | '#') {
            out.push('\\');
        }
        out.push(c);
    }
    out.push('"');
    out
}

/// Builds the text of the Vagrantfile for `cfg`.
///
/// Returns a `String`. Nothing is written to disk here, and
/// nothing is sent anywhere -- `remote::write_file` does that.
///
/// A provider is the thing that actually runs the VM, libvirt
/// or Hyper-V. Both of them happen to spell their settings the
/// same way (`cpus`, `memory`), so the only difference between
/// the two outputs is the provider's name.
///
/// Be careful with that convenience: the Hyper-V version was
/// written from Hyper-V's documentation and **has never started
/// a real machine**. If you are the first person to try it,
/// expect to fix something. See
/// [`Provider`](crate::config::Provider).
#[must_use]
pub fn render(cfg: &Config) -> String {
    let vm = &cfg.vm;
    let source = &cfg.source;
    format!(
        "# Generated by bombyx {version}. Do not edit.
#
# bombyx rewrites this file on every `up`, `provision` and
# `scratch`. Change `bombyx.toml` in the project instead.

Vagrant.configure(\"2\") do |config|
  config.vm.box = {box_name}

  # The default share would mount the workstation's copy of the
  # project at /vagrant, which is the copy this design exists to
  # keep out of the guest. It also hangs on a host whose
  # firewall refuses NFS from the guest bridge.
  config.vm.synced_folder \".\", \"/vagrant\", disabled: true

  config.vm.provider :{provider} do |v|
    v.cpus = {cpus}
    v.memory = {memory}
  end

  config.vm.provision \"shell\",
    path: {bootstrap},
    env: {{
      \"BOMBYX_REPO\" => {repo},
      \"BOMBYX_REF\" => {git_ref},
      \"BOMBYX_SCRIPT\" => {script},
      # Read from the vagrant process on the VM host, which
      # bombyx sets. Vagrant does not export its own
      # environment into a guest, so this hand-over is what
      # makes the two readable inside the VM.
      \"{host_env}\" => ENV.fetch(\"{host_env}\", \"unknown\"),
      \"{hostname_env}\" => ENV.fetch(\"{hostname_env}\", \"unknown\")
    }}
end
",
        version = env!("CARGO_PKG_VERSION"),
        box_name = ruby_string(&vm.box_name),
        provider = vm.provider,
        cpus = vm.cpus,
        memory = vm.memory,
        bootstrap = ruby_string(BOOTSTRAP_NAME),
        repo = ruby_string(source.repo.as_str()),
        git_ref = ruby_string(&source.git_ref),
        script = ruby_string(source.script.as_str()),
        host_env = crate::remote::VM_HOST_ENV,
        hostname_env = crate::remote::VM_HOSTNAME_ENV,
    )
}

/// Every file bombyx writes into the project directory on the
/// VM host, as `(name, contents)` pairs.
///
/// The list exists once, here, and everything else reads it:
/// `plan` to build the write commands, and the tests to check
/// each file is safe to send.
///
/// That is the whole reason for the function. If the list were
/// written out separately in each of those places, adding a
/// third file would mean remembering all of them -- and the one
/// people forget is the test, so the new file would be written
/// to the host without ever being checked.
#[must_use]
pub fn files(cfg: &Config) -> [(&'static str, String); 2] {
    [
        (VAGRANTFILE_NAME, render(cfg)),
        (BOOTSTRAP_NAME, BOOTSTRAP.to_owned()),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{Provider, RepoUrl, ScriptPath, Source, Vm};

    fn cfg_with(provider: Provider) -> Config {
        let mut cfg = Config::for_tests();
        cfg.vm = Vm {
            provider,
            box_name: "generic/ubuntu2204".to_owned(),
            cpus: 4,
            memory: 8192,
        };
        cfg.source = Source {
            repo: RepoUrl::parse("https://example.invalid/p.git")
                .expect("a valid fixture URL"),
            git_ref: "main".to_owned(),
            script: ScriptPath::parse("vagrant/provision.sh")
                .expect("a valid fixture path"),
        };
        cfg
    }

    #[test]
    fn carries_every_configured_value() {
        // Each needle is a whole rendered line, not just the
        // value. Searching for `"4"` alone would pass no matter
        // what: the box name `generic/ubuntu2204` and the
        // version `0.4.1` both contain a 4, so the test would
        // stay green even with `v.cpus` deleted from the
        // template. A test that cannot fail is worse than none,
        // because it looks like cover.
        let out = render(&cfg_with(Provider::Libvirt));
        for needle in [
            "config.vm.box = \"generic/ubuntu2204\"",
            "v.cpus = 4",
            "v.memory = 8192",
            "\"BOMBYX_REPO\" => \"https://example.invalid/p.git\"",
            "\"BOMBYX_REF\" => \"main\"",
            "\"BOMBYX_SCRIPT\" => \"vagrant/provision.sh\"",
        ] {
            assert!(out.contains(needle), "{needle} missing from:\n{out}");
        }
    }

    #[test]
    fn disables_the_default_synced_folder() {
        // Vagrant mounts the Vagrantfile's directory at /vagrant
        // unless told not to. That directory is on the VM host
        // and holds only what bombyx generated, so the mount
        // leaks nothing -- but it hangs on a host whose firewall
        // refuses NFS from the guest bridge, which
        // docs/vm-host-setup.md warns
        // about.
        for provider in [Provider::Libvirt, Provider::Hyperv] {
            let out = render(&cfg_with(provider));
            assert!(
                out.contains(
                    "config.vm.synced_folder \".\", \"/vagrant\", \
                     disabled: true"
                ),
                "{out}"
            );
        }
    }

    #[test]
    fn forwards_the_vm_host_identity_into_the_guest() {
        // A guest has no way to work out which machine is
        // running it. bombyx sets these two variables on the
        // vagrant process on the VM host, but Vagrant does not
        // pass its own environment into a VM, so the
        // Vagrantfile has to hand them over deliberately. Since
        // bombyx writes that file, this is where it happens.
        let out = render(&cfg_with(Provider::Libvirt));
        for var in [crate::remote::VM_HOST_ENV, crate::remote::VM_HOSTNAME_ENV]
        {
            assert!(
                out.contains(&format!(
                    "\"{var}\" => ENV.fetch(\"{var}\", \"unknown\")"
                )),
                "{var} not forwarded:\n{out}"
            );
        }
    }

    #[test]
    fn names_the_provider_it_was_given() {
        assert!(render(&cfg_with(Provider::Libvirt)).contains(":libvirt"));
        assert!(render(&cfg_with(Provider::Hyperv)).contains(":hyperv"));
    }

    #[test]
    fn points_the_provisioner_at_the_bootstrap_script() {
        // The two names must agree or vagrant reports a missing
        // path after bombyx has already created a directory
        // on the host.
        let out = render(&cfg_with(Provider::Libvirt));
        assert!(out.contains(BOOTSTRAP_NAME), "{out}");
        assert!(out.contains("config.vm.provision"), "{out}");
    }

    #[test]
    fn escapes_a_quote_that_validation_would_have_refused() {
        // `Config::validate` refuses these fields outright, so
        // this path is unreachable through `bombyx.toml`. It is
        // reachable through the library, whose `Config` fields
        // are public, and an unescaped quote there would end the
        // Ruby literal and change what the file means.
        let mut cfg = cfg_with(Provider::Libvirt);
        cfg.vm.box_name = "a\"b".to_owned();
        let out = render(&cfg);
        assert!(out.contains("a\\\"b"), "{out}");
    }

    #[test]
    fn the_bootstrap_script_guards_every_variable_it_needs() {
        // Without the `:?` guards an unset variable clones into
        // an empty path as root.
        for guard in ["BOMBYX_REPO:?", "BOMBYX_REF:?", "BOMBYX_SCRIPT:?"] {
            assert!(BOOTSTRAP.contains(guard), "{guard} missing");
        }
        assert!(BOOTSTRAP.contains("set -euo pipefail"));
    }
}
