//! Renders the two files bombyx writes on the VM host: the
//! Vagrantfile and the bootstrap script.
//!
//! bombyx generates the Vagrantfile rather than taking one from
//! the project, because the project's files do not exist
//! anywhere Vagrant can read them before the VM boots. See
//! `docs/trust-boundary.md` for why that is the arrangement.
//!
//! Two files, and the split is deliberate. The Vagrantfile
//! varies per project and is rendered here. [`BOOTSTRAP`] is
//! identical everywhere, so it ships verbatim and nothing is
//! interpolated into it -- which keeps config values out of
//! shell text this module composes.

use crate::config::Config;

/// The provisioning script, shipped to the host unchanged.
///
/// Held as a file rather than a string literal so it is
/// syntax-highlighted, `shellcheck`-able and diffable.
pub const BOOTSTRAP: &str = include_str!("../templates/bootstrap.sh");

/// The Vagrantfile's name on the VM host.
pub const VAGRANTFILE_NAME: &str = "Vagrantfile";

/// The bootstrap script's name on the VM host.
///
/// The Vagrantfile's `path:` is relative to the directory the
/// Vagrantfile is in, so the two names have to agree and are
/// stated once here.
pub const BOOTSTRAP_NAME: &str = "bootstrap.sh";

/// Escapes `value` for a double-quoted Ruby string literal.
///
/// Three characters matter. A double quote ends the literal, a
/// backslash starts an escape, and `#` begins interpolation
/// (`#{...}`), which Ruby evaluates. Escaping every `#` rather
/// than only the `#{` pair is deliberate: `\#` is just `#` in
/// Ruby, so the blunt rule costs nothing and cannot be defeated
/// by a spelling this one did not anticipate.
///
/// [`Config::validate`](crate::config::Config) refuses all three
/// in the fields that reach here, so through `bombyx.toml` this
/// is unreachable. It is reachable through the library, whose
/// `Config` fields are public, and the renderer should not
/// depend on a guard living in another module to be correct.
fn ruby_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for c in value.chars() {
        if matches!(c, '"' | '\\' | '#') {
            out.push('\\');
        }
        out.push(c);
    }
    out.push('"');
    out
}

/// Renders the Vagrantfile for `cfg`.
///
/// Both providers take `cpus` and `memory` under the same
/// names, so only the provider symbol differs. The Hyper-V
/// spelling is written from that provider's documented options
/// and **has never booted a machine** -- see
/// [`Provider`](crate::config::Provider).
#[must_use]
pub fn render(cfg: &Config) -> String {
    let vm = &cfg.vm;
    let source = &cfg.source;
    format!(
        "# Generated by bombyx {version}. Do not edit.
#
# bombyx rewrites this file on every `up`, `provision` and
# `scratch`. Change `bombyx.toml` in the project instead.

Vagrant.configure(\"2\") do |config|
  config.vm.box = {box_name}

  # The default share would mount the workstation's copy of the
  # project at /vagrant, which is the copy this design exists to
  # keep out of the guest. It also hangs on a host whose
  # firewall refuses NFS from the guest bridge.
  config.vm.synced_folder \".\", \"/vagrant\", disabled: true

  config.vm.provider :{provider} do |v|
    v.cpus = {cpus}
    v.memory = {memory}
  end

  config.vm.provision \"shell\",
    path: {bootstrap},
    env: {{
      \"BOMBYX_REPO\" => {repo},
      \"BOMBYX_REF\" => {git_ref},
      \"BOMBYX_SCRIPT\" => {script},
      # Read from the vagrant process on the VM host, which
      # bombyx sets. Vagrant does not export its own
      # environment into a guest, so this hand-over is what
      # makes the two readable inside the VM.
      \"{host_env}\" => ENV.fetch(\"{host_env}\", \"unknown\"),
      \"{hostname_env}\" => ENV.fetch(\"{hostname_env}\", \"unknown\")
    }}
end
",
        version = env!("CARGO_PKG_VERSION"),
        box_name = ruby_string(&vm.box_name),
        provider = vm.provider,
        cpus = vm.cpus,
        memory = vm.memory,
        bootstrap = ruby_string(BOOTSTRAP_NAME),
        repo = ruby_string(&source.repo),
        git_ref = ruby_string(&source.git_ref),
        script = ruby_string(&source.script),
        host_env = crate::remote::VM_HOST_ENV,
        hostname_env = crate::remote::VM_HOSTNAME_ENV,
    )
}

/// The files bombyx writes into the remote project directory.
///
/// One list, used by `plan` to build the write commands and by
/// the tests that assert the heredoc invariant holds for every
/// payload. Enumerating them separately in each place is how a
/// third file would end up written but unchecked.
#[must_use]
pub fn files(cfg: &Config) -> [(&'static str, String); 2] {
    [
        (VAGRANTFILE_NAME, render(cfg)),
        (BOOTSTRAP_NAME, BOOTSTRAP.to_owned()),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{Provider, Source, Vm};

    fn cfg_with(provider: Provider) -> Config {
        let mut cfg = Config::for_tests();
        cfg.vm = Vm {
            provider,
            box_name: "generic/ubuntu2204".to_owned(),
            cpus: 4,
            memory: 8192,
        };
        cfg.source = Source {
            repo: "https://example.invalid/p.git".to_owned(),
            git_ref: "main".to_owned(),
            script: "vagrant/provision.sh".to_owned(),
        };
        cfg
    }

    #[test]
    fn carries_every_configured_value() {
        // Pins the rendered line, not the value. The first cut
        // asserted `out.contains("4")` for `cpus = 4`, which the
        // box name `generic/ubuntu2204` and the version `0.4.1`
        // both satisfy -- so deleting `v.cpus` from the template
        // left the test green. Both reviewers caught it.
        let out = render(&cfg_with(Provider::Libvirt));
        for needle in [
            "config.vm.box = \"generic/ubuntu2204\"",
            "v.cpus = 4",
            "v.memory = 8192",
            "\"BOMBYX_REPO\" => \"https://example.invalid/p.git\"",
            "\"BOMBYX_REF\" => \"main\"",
            "\"BOMBYX_SCRIPT\" => \"vagrant/provision.sh\"",
        ] {
            assert!(out.contains(needle), "{needle} missing from:\n{out}");
        }
    }

    #[test]
    fn disables_the_default_synced_folder() {
        // Vagrant mounts the Vagrantfile's directory at /vagrant
        // unless told not to, and that directory is the copy of
        // the project pushed from the workstation -- the copy
        // this whole design exists to keep out of the guest. It
        // also hangs on a host whose firewall refuses NFS from
        // the guest bridge, which docs/vm-host-setup.md warns
        // about.
        for provider in [Provider::Libvirt, Provider::Hyperv] {
            let out = render(&cfg_with(provider));
            assert!(
                out.contains(
                    "config.vm.synced_folder \".\", \"/vagrant\", \
                     disabled: true"
                ),
                "{out}"
            );
        }
    }

    #[test]
    fn forwards_the_vm_host_identity_into_the_guest() {
        // A guest cannot work out which machine it runs on, so
        // bombyx sets these on the vagrant process and the
        // Vagrantfile hands them over. The project's own
        // Vagrantfile used to do it; bombyx overwrites that file
        // now, so the generated one has to.
        let out = render(&cfg_with(Provider::Libvirt));
        for var in [crate::remote::VM_HOST_ENV, crate::remote::VM_HOSTNAME_ENV]
        {
            assert!(
                out.contains(&format!(
                    "\"{var}\" => ENV.fetch(\"{var}\", \"unknown\")"
                )),
                "{var} not forwarded:\n{out}"
            );
        }
    }

    #[test]
    fn names_the_provider_it_was_given() {
        assert!(render(&cfg_with(Provider::Libvirt)).contains(":libvirt"));
        assert!(render(&cfg_with(Provider::Hyperv)).contains(":hyperv"));
    }

    #[test]
    fn points_the_provisioner_at_the_bootstrap_script() {
        // The two names must agree or vagrant reports a missing
        // path after the push has already changed state.
        let out = render(&cfg_with(Provider::Libvirt));
        assert!(out.contains(BOOTSTRAP_NAME), "{out}");
        assert!(out.contains("config.vm.provision"), "{out}");
    }

    #[test]
    fn escapes_a_quote_that_validation_would_have_refused() {
        // `Config::validate` refuses these fields outright, so
        // this path is unreachable through `bombyx.toml`. It is
        // reachable through the library, whose `Config` fields
        // are public, and an unescaped quote there would end the
        // Ruby literal and change what the file means.
        let mut cfg = cfg_with(Provider::Libvirt);
        cfg.vm.box_name = "a\"b".to_owned();
        let out = render(&cfg);
        assert!(out.contains("a\\\"b"), "{out}");
    }

    #[test]
    fn the_bootstrap_script_guards_every_variable_it_needs() {
        // Without the `:?` guards an unset variable clones into
        // an empty path as root.
        for guard in ["BOMBYX_REPO:?", "BOMBYX_REF:?", "BOMBYX_SCRIPT:?"] {
            assert!(BOOTSTRAP.contains(guard), "{guard} missing");
        }
        assert!(BOOTSTRAP.contains("set -euo pipefail"));
    }
}
