# Generated by bombyx. Do not edit: bombyx rewrites it on every
# `up`, `provision` and `scratch`.
#
# Sets up the agent's account on a Windows guest, then hands
# bootstrap.ps1 to it. The Vagrantfile's shell provisioner runs
# this as the account vagrant logs in as, which is an
# administrator on the box bombyx targets. Nothing from the
# project's repository runs before the hand-over.
#
# Every value arrives base64-encoded in an environment variable,
# because vagrant writes each into this script as
# $env:NAME="value" and escapes nothing. BOMBYX_PRESERVE_ENV lists
# the names; each is decoded before use.
#
# Windows has no `sudo -u`, so the hand-over is an SSH login from
# this guest to itself, as the agent, with a key this script makes
# and authorizes. The login runs a small script that sets the
# decoded variables and then runs bootstrap.ps1.
#
# Targets Windows PowerShell 5.1, which is what vagrant runs.

$ErrorActionPreference = 'Stop'
# PowerShell otherwise writes progress records to stderr as
# CLIXML, which bombyx would print as the reason for a failure.
$ProgressPreference = 'SilentlyContinue'
Set-StrictMode -Version 2.0

# Git for Windows' minimal build, pinned. The guest refuses a
# download whose SHA-256 differs, so the pin is the version, the
# URL and the hash together. The hash is the one GitHub publishes
# for the release asset. Bumping git is a change to these three
# lines.
$MinGitVersion = '2.55.0.5'
$MinGitUrl = 'https://github.com/git-for-windows/git/releases/' +
    'download/v2.55.0.windows.5/MinGit-2.55.0.5-64-bit.zip'
$MinGitSha256 =
    '56D7B226B7693196CFC71FEF26568F536C4A021AB6C37FF2DB4287BED908E96E'

# Where vagrant staged bootstrap.ps1: `.bombyx-staging` in the home
# of the account it logs in as.
$Staging = Join-Path $env:USERPROFILE '.bombyx-staging'
# Everything bombyx installs. Under Program Files, so only an
# administrator can change it: the agent and vagrant's login account,
# and no other account the box ships enabled.
$InstallDir = Join-Path $env:ProgramFiles 'bombyx'
$GitDir = Join-Path $InstallDir 'git'
$Bootstrap = Join-Path $InstallDir 'bootstrap.ps1'
# Which account this VM was set up for.
$AccountRecord = Join-Path $InstallDir 'guest-user'
# The hand-over key and the guest's own host key, in the login
# account's home, where only it and the administrators can read.
$LoginSsh = Join-Path $env:USERPROFILE '.ssh'
$HandoverKey = Join-Path $LoginSsh 'bombyx-handover'
$LocalKnownHosts = Join-Path $LoginSsh 'bombyx-localhost-known-hosts'
$Ssh = Join-Path $env:SystemRoot 'System32\OpenSSH\ssh.exe'
$SshKeygen = Join-Path $env:SystemRoot 'System32\OpenSSH\ssh-keygen.exe'

# The well-known SIDs, so nothing here depends on the language
# the box was installed in.
$AdministratorsSid = 'S-1-5-32-544'
$SystemSid = 'S-1-5-18'

# The agent-profile paths a credential may sit at, set just before
# the first one is placed. bootstrap.ps1 removes a secret the config
# dropped and refuses a missing one, but it never runs after a
# refusal here, so Refuse removes all of them, as account.sh does.
$AgentSecrets = @()

# Prints `why` to stderr with bombyx's prefix and exits 1. Removes
# the staging directory and every path in $AgentSecrets first, as
# account.sh does.
function Refuse([string] $Why) {
    foreach ($path in $AgentSecrets) {
        Remove-Item -LiteralPath $path -Force -ErrorAction SilentlyContinue
        if (Test-Path -LiteralPath $path) {
            [Console]::Error.WriteLine(
                "bombyx: A CREDENTIAL IS STILL AT $path, because it " +
                'could not be removed. Remove it in the guest.')
        }
    }
    if (Test-Path -LiteralPath $Staging) {
        Remove-Item -LiteralPath $Staging -Recurse -Force `
            -ErrorAction SilentlyContinue
        if (Test-Path -LiteralPath $Staging) {
            [Console]::Error.WriteLine(
                "bombyx: could not remove $Staging. Remove it in " +
                'the guest.')
        }
    }
    [Console]::Error.WriteLine("bombyx: $Why")
    exit 1
}

# The reason given when the Vagrantfile and this script disagree.
$VersionSkew = 'The generated Vagrantfile and this script came from ' +
    'different versions of bombyx.'

# The raw base64 value of environment variable `name`, refusing one
# that is not base64. An empty value arrives as no variable at all,
# because Windows deletes a variable set to the empty string, so a
# missing one is the empty string. The hand-over pastes the value
# between single quotes, and base64 holds no quote, so this check is
# what keeps that paste safe. `\z` rather than `$`, which would also
# match before a final newline. The value is decoded here too, so one
# the pattern admits but base64 does not, such as a length that is
# not a multiple of four, is refused here rather than in the agent's
# hand-over.
function Get-Base64Env([string] $Name) {
    $raw = [Environment]::GetEnvironmentVariable($Name)
    if ([string]::IsNullOrEmpty($raw)) {
        return ''
    }
    if ($raw -cnotmatch '^[A-Za-z0-9+/]*={0,2}\z') {
        Refuse "$Name is not base64. $VersionSkew"
    }
    try {
        [void][Convert]::FromBase64String($raw)
    } catch {
        Refuse "$Name is not base64. $VersionSkew"
    }
    return $raw
}

# The value of environment variable `name`, decoded from base64.
function Decode([string] $Name) {
    return [Text.Encoding]::UTF8.GetString(
        [Convert]::FromBase64String((Get-Base64Env $Name)))
}

# Grants `sid`, SYSTEM and the administrators full control of
# `path`, removes every inherited entry, and makes `sid` the
# owner. The Windows counterpart of chown and mode 0600: sshd
# refuses an authorized_keys file other accounts can write.
function Protect([string] $Path, [string] $Sid) {
    $inherit = ''
    if (Test-Path -LiteralPath $Path -PathType Container) {
        $inherit = '(OI)(CI)'
    }
    $out = & icacls.exe $Path /inheritance:r /grant:r `
        "*${Sid}:${inherit}F" "*${SystemSid}:${inherit}F" `
        "*${AdministratorsSid}:${inherit}F" 2>&1
    if ($LASTEXITCODE -ne 0) {
        Refuse "could not set the permissions on ${Path}: $out"
    }
    $out = & icacls.exe $Path /setowner "*$Sid" 2>&1
    if ($LASTEXITCODE -ne 0) {
        Refuse "could not make $Path the agent's: $out"
    }
}

# Puts the secret `what` at `target` in the agent's profile, or
# takes it away, by the flag `present`. Each case refuses when a
# copy it must remove stays, because a stale copy would pass for a
# current one:
#
# - "0": the config dropped the secret. The copy is removed here,
#   before the hand-over, so no later failure leaves it in the guest.
# - "1" with nothing staged as `stagedName`: the copy is removed, and
#   bootstrap.ps1 refuses the missing file.
# - "1" with the file staged: it moves to `target`, readable by the
#   agent, SYSTEM and the administrators alone. The file is created
#   empty and protected before it holds the secret, so no moment
#   leaves it with the folder's inherited permissions.
function Place([string] $Present, [string] $What, [string] $StagedName,
        [string] $Target, [string] $Sid) {
    if ($Present -ne '1') {
        Remove-Item -LiteralPath $Target -Force -ErrorAction SilentlyContinue
        if (Test-Path -LiteralPath $Target) {
            Refuse ("the config names no $What, and the copy at " +
                "$Target could not be removed")
        }
        return
    }
    $source = Join-Path $Staging $StagedName
    if (-not (Test-Path -LiteralPath $source -PathType Leaf)) {
        Remove-Item -LiteralPath $Target -Force -ErrorAction SilentlyContinue
        if (Test-Path -LiteralPath $Target) {
            Refuse ("the configured $What did not arrive, and the copy " +
                "at $Target from an earlier provision could not be " +
                'removed')
        }
        return
    }
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $Target) |
        Out-Null
    # Removed first, so the new file starts from the folder's
    # inherited entries, which Protect strips. Truncating an old copy
    # would keep any entry granted on it since the last provision.
    Remove-Item -LiteralPath $Target -Force -ErrorAction SilentlyContinue
    if (Test-Path -LiteralPath $Target) {
        Refuse ("could not replace $Target, the copy an earlier " +
            'provision placed')
    }
    [IO.File]::WriteAllBytes($Target, [byte[]]@())
    Protect $Target $Sid
    [IO.File]::WriteAllBytes($Target, [IO.File]::ReadAllBytes($source))
}

# Asks Windows to create the account's profile, which it otherwise
# does at the first logon. The hand-over key has to sit in the
# profile before that logon. A folder made by hand instead would
# be taken by Windows for someone else's, and the profile would
# land beside it with a suffix.
function New-Profile([string] $Sid, [string] $Name) {
    $signature = @'
[DllImport("userenv.dll", CharSet = CharSet.Unicode)]
public static extern int CreateProfile(
    string sid, string name, System.Text.StringBuilder path, uint size);
'@
    $userenv = Add-Type -MemberDefinition $signature -Name UserEnv `
        -Namespace Bombyx -PassThru
    $path = New-Object Text.StringBuilder 260
    $result = $userenv::CreateProfile($Sid, $Name, $path, 260)
    if ($result -ne 0) {
        Refuse ("Windows could not create a profile for $Name " +
            ('(CreateProfile returned 0x{0:X8}).' -f $result))
    }
}

try {
    $User = Decode 'BOMBYX_GUEST_USER'
    # The rules GuestUser applies, plus Windows' 20-character cap.
    # bombyx checked them when it read the config; checking here
    # too keeps a Vagrantfile from another version from reaching
    # New-LocalUser with a name nobody checked.
    if ($User -cnotmatch '^[a-z_][a-z0-9_-]{0,19}$') {
        Refuse "guest_user (`"$User`") is not an account name bombyx creates."
    }
    # Groups share one namespace with accounts, so a group's name
    # cannot be an account either.
    $builtIn = @('administrator', 'guest', 'defaultaccount',
        'wdagutilityaccount', 'administrators', 'users', 'guests',
        'replicator', 'root', 'vagrant')
    if ($builtIn -contains $User -or $User -eq $env:USERNAME) {
        Refuse ("guest_user (`"$User`") is a built-in account or group, " +
            'or the account Vagrant logs in as. The agent needs an ' +
            'account of its own.')
    }
    # A device name cannot be the account's profile folder.
    if ($User -match '^(con|prn|aux|nul|com[1-9]|lpt[1-9])$') {
        Refuse ("guest_user (`"$User`") is a name Windows reserves " +
            'for a device.')
    }

    $Preserve = Decode 'BOMBYX_PRESERVE_ENV'
    if ($Preserve -cnotmatch '^[A-Za-z_][A-Za-z0-9_]*(,[A-Za-z_][A-Za-z0-9_]*)*$') {
        Refuse ('BOMBYX_PRESERVE_ENV is missing or holds something ' +
            "other than variable names. $VersionSkew")
    }

    $staged = Join-Path $Staging 'bootstrap.ps1'
    if (-not (Test-Path -LiteralPath $staged -PathType Leaf)) {
        Refuse ("bootstrap.ps1 did not arrive at $staged, so there " +
            "is nothing to hand to the agent's account.")
    }
    # The secrets refresh a running guest's `up` and `shell` call, and
    # the runner it starts for the project's hook, each with the path
    # it is installed at. bombyx names them rather than sending them,
    # because they are too long for the guest's command line.
    $helpers = @(
        @((Join-Path $Staging 'refresh.ps1'),
            (Join-Path $InstallDir 'refresh.ps1')),
        @((Join-Path $Staging 'hook.ps1'),
            (Join-Path $InstallDir 'hook.ps1')))
    foreach ($helper in $helpers) {
        if (-not (Test-Path -LiteralPath $helper[0] -PathType Leaf)) {
            Refuse "$($helper[0]) did not arrive. $VersionSkew"
        }
    }
    foreach ($tool in @($Ssh, $SshKeygen)) {
        if (-not (Test-Path -LiteralPath $tool -PathType Leaf)) {
            Refuse ("$tool is not on this box, and bombyx needs it to " +
                "hand over to the agent's account. Choose a box that " +
                'has the OpenSSH client.')
        }
    }

    New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
    if (Test-Path -LiteralPath $AccountRecord) {
        $recorded = (Get-Content -LiteralPath $AccountRecord -Raw).Trim()
        if ($recorded -ne $User) {
            Refuse ("this VM was set up for guest_user `"$recorded`", " +
                "and the config now names `"$User`". bombyx does not " +
                'move a VM from one account to another; run bombyx ' +
                'destroy, then bombyx up.')
        }
    }

    # The account. Its password is random and kept nowhere: the
    # agent logs in with the hand-over key alone.
    $account = Get-LocalUser -Name $User -ErrorAction SilentlyContinue
    if ($null -eq $account) {
        $bytes = New-Object byte[] 24
        [Security.Cryptography.RandomNumberGenerator]::Create().GetBytes(
            $bytes)
        # The suffix meets Windows' complexity rule whatever the
        # random part holds.
        $password = ConvertTo-SecureString -AsPlainText -Force `
            ([Convert]::ToBase64String($bytes) + 'aA1!')
        $account = New-LocalUser -Name $User -Password $password `
            -PasswordNeverExpires -AccountNeverExpires `
            -Description 'The account bombyx runs the agent as'
    }
    $sid = $account.SID.Value
    Set-Content -LiteralPath $AccountRecord -Value $User -Encoding ASCII

    # An administrator, the Windows counterpart of the Linux agent's
    # passwordless sudo: the agent installs what its build needs.
    $admins = Get-LocalGroupMember -SID $AdministratorsSid |
        Where-Object { $_.SID.Value -eq $sid }
    if ($null -eq $admins) {
        Add-LocalGroupMember -SID $AdministratorsSid -Member $sid
    }

    $profileKey = 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\' +
        "ProfileList\$sid"
    if (-not (Test-Path -LiteralPath $profileKey)) {
        New-Profile $sid $User
    }
    $AgentHome = (Get-ItemProperty -LiteralPath $profileKey).ProfileImagePath
    # The profile must sit at the plain name. Any other path means a
    # folder of that name existed before the account, owned by
    # whoever made it, and the hand-over key and the clone would then
    # go into a profile beside a folder bombyx does not control.
    $expected = Join-Path (Split-Path -Parent $env:USERPROFILE) $User
    if ($AgentHome -ne $expected -or
        -not (Test-Path -LiteralPath $AgentHome -PathType Container)) {
        Refuse ("the account $User has its profile at `"$AgentHome`", " +
            "and bombyx needs it at $expected. A folder of that name " +
            'probably existed before the account did. Choose another ' +
            'guest_user, or run bombyx destroy, then bombyx up.')
    }

    # git, unless this version is already installed.
    $gitExe = Join-Path $GitDir 'cmd\git.exe'
    $versionFile = Join-Path $GitDir 'bombyx-version'
    $installed = ''
    if (Test-Path -LiteralPath $versionFile) {
        $installed = (Get-Content -LiteralPath $versionFile -Raw).Trim()
    }
    if (-not (Test-Path -LiteralPath $gitExe) -or
        $installed -ne $MinGitVersion) {
        Write-Output "bombyx: installing git $MinGitVersion"
        # Windows PowerShell 5.1 offers TLS 1.0 by default, which
        # GitHub refuses.
        [Net.ServicePointManager]::SecurityProtocol =
            [Net.SecurityProtocolType]::Tls12
        $zip = Join-Path $env:TEMP "bombyx-mingit-$MinGitVersion.zip"
        try {
            Invoke-WebRequest -UseBasicParsing -Uri $MinGitUrl `
                -OutFile $zip
        } catch {
            Refuse ("could not download git from ${MinGitUrl}: " +
                $_.Exception.Message)
        }
        $hash = (Get-FileHash -Algorithm SHA256 -LiteralPath $zip).Hash
        if ($hash -ne $MinGitSha256) {
            Remove-Item -LiteralPath $zip -Force
            Refuse ("the git download from $MinGitUrl has SHA-256 " +
                "$hash, and bombyx expects $MinGitSha256. Refusing to " +
                'install it.')
        }
        # Unpacked beside the old copy and moved into place, so a
        # failure part-way leaves the old copy or none, never half.
        $unpack = "$GitDir.new"
        if (Test-Path -LiteralPath $unpack) {
            Remove-Item -LiteralPath $unpack -Recurse -Force
        }
        Expand-Archive -LiteralPath $zip -DestinationPath $unpack
        Remove-Item -LiteralPath $zip -Force
        Set-Content -LiteralPath (Join-Path $unpack 'bombyx-version') `
            -Value $MinGitVersion -Encoding ASCII
        if (Test-Path -LiteralPath $GitDir) {
            Remove-Item -LiteralPath $GitDir -Recurse -Force
        }
        Move-Item -LiteralPath $unpack -Destination $GitDir
    }
    # On the machine's PATH, so the agent's own shells find git as a
    # Linux agent does. bootstrap.ps1 does not rely on it.
    $gitCmd = Join-Path $GitDir 'cmd'
    $machinePath = [Environment]::GetEnvironmentVariable('Path', 'Machine')
    if (($machinePath -split ';') -notcontains $gitCmd) {
        [Environment]::SetEnvironmentVariable(
            'Path', "$machinePath;$gitCmd", 'Machine')
    }

    # The credentials, while the staging directory still holds them,
    # at the paths bootstrap.ps1 reads.
    $deployKey = Join-Path $AgentHome '.ssh\bombyx-deploy-key'
    $envFile = Join-Path $AgentHome '.bombyx-env'
    $gitCred = Join-Path $AgentHome '.bombyx-git-credentials'
    $script:AgentSecrets = @($deployKey, $envFile, $gitCred)
    # Each variable is a "1"/"0" flag, the deploy key's included. Its
    # name lacks `_PRESENT` because it is the Linux scripts' flag too.
    Place (Decode 'BOMBYX_DEPLOY_KEY') 'deploy key' 'deploy-key' `
        $deployKey $sid
    Place (Decode 'BOMBYX_ENV_FILE_PRESENT') 'env_file' 'env' $envFile $sid
    Place (Decode 'BOMBYX_GIT_CRED_PRESENT') 'git credential for repo_token' `
        'git-credentials' $gitCred $sid

    # bootstrap.ps1 and the helpers, installed afresh on every
    # provision. bootstrap.ps1 runs only right after, so the agent's
    # own edits to an earlier copy never run. The helpers run between
    # provisions, when `up` and `shell` call them, so the agent, an
    # administrator, can change them in that time, as it could change
    # anything else on the guest.
    Copy-Item -LiteralPath $staged -Destination $Bootstrap -Force
    foreach ($helper in $helpers) {
        Copy-Item -LiteralPath $helper[0] -Destination $helper[1] -Force
    }
    Remove-Item -LiteralPath $Staging -Recurse -Force

    # The hand-over key, made once and kept, so a later provision
    # finds the same key authorized.
    New-Item -ItemType Directory -Force -Path $LoginSsh | Out-Null
    if (-not (Test-Path -LiteralPath $HandoverKey)) {
        # Start-Process takes the command line as written, so the
        # empty passphrase reaches ssh-keygen as `""`, which it reads
        # as empty. Passed through `&`, the quoting would depend on
        # the PowerShell version.
        $keygen = Start-Process -FilePath $SshKeygen -Wait -PassThru `
            -NoNewWindow -ArgumentList ('-q -t ed25519 -N "" ' +
                "-C bombyx-handover -f `"$HandoverKey`"")
        if ($keygen.ExitCode -ne 0) {
            Refuse "could not make the hand-over key at $HandoverKey."
        }
    }
    $public = (Get-Content -LiteralPath "$HandoverKey.pub" -Raw).Trim()

    # Authorized in the agent's own .ssh. sshd reads that file for
    # an administrator too on this box, because its sshd_config
    # leaves the administrators_authorized_keys block commented out.
    $agentSsh = Join-Path $AgentHome '.ssh'
    New-Item -ItemType Directory -Force -Path $agentSsh | Out-Null
    Protect $agentSsh $sid
    $authorized = Join-Path $agentSsh 'authorized_keys'
    $lines = @()
    if (Test-Path -LiteralPath $authorized) {
        $lines = @(Get-Content -LiteralPath $authorized)
    }
    if ($lines -notcontains $public) {
        Set-Content -LiteralPath $authorized -Value ($lines + $public) `
            -Encoding ASCII
    }
    Protect $authorized $sid

    # The guest's own host key, so the login checks it strictly
    # rather than trusting whatever answers on localhost.
    $hostKey = Join-Path $env:ProgramData 'ssh\ssh_host_ed25519_key.pub'
    if (-not (Test-Path -LiteralPath $hostKey)) {
        Refuse ("sshd's host key is not at $hostKey, so bombyx cannot " +
            'check the login it hands over through.')
    }
    $parts = (Get-Content -LiteralPath $hostKey -Raw).Trim() -split '\s+'
    Set-Content -LiteralPath $LocalKnownHosts -Encoding ASCII `
        -Value "localhost $($parts[0]) $($parts[1])"

    # An unactivated evaluation shuts down 10 days after its first
    # boot. bombyx does not activate it, because activating contacts
    # Microsoft; it says how long is left. The ID is Windows' own
    # application ID in the licensing service.
    try {
        $licence = Get-CimInstance -ClassName SoftwareLicensingProduct `
            -Filter ("ApplicationID='55c92734-d682-4d71-983e-d6ec3f16059f'" +
                ' AND PartialProductKey IS NOT NULL') |
            Select-Object -First 1
        if ($null -ne $licence -and $licence.LicenseStatus -ne 1) {
            $days = [math]::Floor($licence.GracePeriodRemaining / 1440)
            Write-Output ("bombyx: this Windows evaluation is not " +
                "activated and shuts down in about $days days unless it " +
                'is. To activate it, run in the guest: cscript //nologo ' +
                'C:\Windows\System32\slmgr.vbs /ato')
        }
    } catch {
        Write-Output ('bombyx: could not read whether Windows is ' +
            'activated. An unactivated evaluation shuts down 10 days ' +
            'after its first boot.')
    }

    # The script the login runs: each preserved variable set from
    # its base64, then bootstrap.ps1. The names matched the pattern
    # above and each value passed Get-Base64Env's check, so neither
    # can close the quotes it is pasted into. Written to the
    # agent's home, protected before it holds anything.
    $handover = Join-Path $AgentHome '.bombyx-handover.ps1'
    Set-Content -LiteralPath $handover -Value '' -Encoding ASCII
    Protect $handover $sid
    $body = New-Object Text.StringBuilder
    # So that a failure while setting a variable ends the hand-over
    # rather than running bootstrap.ps1 without it.
    [void]$body.AppendLine('$ErrorActionPreference = ''Stop''')
    foreach ($name in $Preserve -split ',') {
        $raw = Get-Base64Env $name
        [void]$body.AppendLine(
            "`$env:$name = [Text.Encoding]::UTF8.GetString(" +
            "[Convert]::FromBase64String('$raw'))")
    }
    [void]$body.AppendLine(
        "& '$($Bootstrap -replace "'", "''")'")
    [void]$body.AppendLine('exit $LASTEXITCODE')
    Set-Content -LiteralPath $handover -Value $body.ToString() `
        -Encoding ASCII

    # The hand-over. BatchMode keeps ssh from asking for anything,
    # -n gives it no stdin, and -T asks for no terminal. The remote
    # command reaches sshd's default shell, cmd.exe unless the box
    # names another, and holds no character that cmd.exe or
    # PowerShell reads.
    #
    # ssh's stderr is not redirected: with `2>&1`, Windows' ssh
    # client and PowerShell 5.1 stop after the first line of output
    # and never return, whatever the remote side runs. Unredirected,
    # its output passes straight through, and 'Continue' keeps any
    # stderr PowerShell does see from ending this script.
    $ErrorActionPreference = 'Continue'
    & $Ssh -n -T -i $HandoverKey -o IdentitiesOnly=yes `
        -o BatchMode=yes -o StrictHostKeyChecking=yes `
        -o "UserKnownHostsFile=$LocalKnownHosts" `
        "$User@localhost" powershell.exe -NoProfile -NonInteractive `
        -ExecutionPolicy Bypass -File $handover
    $code = $LASTEXITCODE
    $ErrorActionPreference = 'Stop'
    # ssh exits 255 when the connection or the login fails, so 255 is
    # read as that. A remote script exiting 255 is read the same way,
    # which is why the message says what to check rather than what
    # happened.
    # Not a Refuse: the project's script may have exited 255 after
    # using the secrets, and they are ones the config grants.
    if ($code -eq 255) {
        [Console]::Error.WriteLine(
            "bombyx: the SSH login to $User@localhost failed, so " +
            "bootstrap.ps1 did not run as $User. If this box's " +
            'sshd_config enables the administrators_authorized_keys ' +
            "block, sshd ignores $authorized for an administrator.")
    }
    exit $code
} catch {
    Refuse ('the account setup stopped on an unexpected error: ' +
        $_.Exception.Message)
}
