# Generated by bombyx. Do not edit: bombyx rewrites it on every
# `up`, `provision` and `scratch`.
#
# Sets up the agent's account on a Windows guest, then hands
# bootstrap.ps1 to it. The Vagrantfile's shell provisioner runs
# this as the account vagrant logs in as, which is an
# administrator on the box bombyx targets. Nothing from the
# project's repository runs before the hand-over.
#
# Every value arrives base64-encoded in an environment variable,
# because vagrant writes each into this script as
# $env:NAME="value" and escapes nothing. BOMBYX_PRESERVE_ENV lists
# the names; each is decoded before use.
#
# Windows has no `sudo -u`, so the hand-over is an SSH login from
# this guest to itself, as the agent, with a key this script makes
# and authorizes. The login runs a small script that sets the
# decoded variables and then runs bootstrap.ps1.
#
# Targets Windows PowerShell 5.1, which is what vagrant runs.

$ErrorActionPreference = 'Stop'
# PowerShell otherwise writes progress records to stderr as
# CLIXML, which bombyx would print as the reason for a failure.
$ProgressPreference = 'SilentlyContinue'
Set-StrictMode -Version 2.0

# Git for Windows' minimal build, pinned. The guest refuses a
# download whose SHA-256 differs, so the pin is the version, the
# URL and the hash together. The hash is the one GitHub publishes
# for the release asset. Bumping git is a change to these three
# lines.
$MinGitVersion = '2.55.0.5'
$MinGitUrl = 'https://github.com/git-for-windows/git/releases/' +
    'download/v2.55.0.windows.5/MinGit-2.55.0.5-64-bit.zip'
$MinGitSha256 =
    '56D7B226B7693196CFC71FEF26568F536C4A021AB6C37FF2DB4287BED908E96E'

# Where vagrant staged bootstrap.ps1: `.bombyx-staging` in the home
# of the account it logs in as.
$Staging = Join-Path $env:USERPROFILE '.bombyx-staging'
# Everything bombyx installs. Under Program Files, so only an
# administrator can change it: the agent is one, but no other
# account on the guest is.
$InstallDir = Join-Path $env:ProgramFiles 'bombyx'
$GitDir = Join-Path $InstallDir 'git'
$Bootstrap = Join-Path $InstallDir 'bootstrap.ps1'
# Which account this VM was set up for.
$AccountRecord = Join-Path $InstallDir 'guest-user'
# The hand-over key and the guest's own host key, in the login
# account's home, where only it and the administrators can read.
$LoginSsh = Join-Path $env:USERPROFILE '.ssh'
$HandoverKey = Join-Path $LoginSsh 'bombyx-handover'
$LocalKnownHosts = Join-Path $LoginSsh 'bombyx-localhost-known-hosts'
$Ssh = Join-Path $env:SystemRoot 'System32\OpenSSH\ssh.exe'
$SshKeygen = Join-Path $env:SystemRoot 'System32\OpenSSH\ssh-keygen.exe'

# The well-known SIDs, so nothing here depends on the language
# the box was installed in.
$AdministratorsSid = 'S-1-5-32-544'
$SystemSid = 'S-1-5-18'

# Prints `why` to stderr with bombyx's prefix and exits 1. Removes
# the staging directory first, as account.sh does.
function Refuse([string] $Why) {
    if (Test-Path -LiteralPath $Staging) {
        Remove-Item -LiteralPath $Staging -Recurse -Force `
            -ErrorAction SilentlyContinue
        if (Test-Path -LiteralPath $Staging) {
            [Console]::Error.WriteLine(
                "bombyx: could not remove $Staging. Remove it in " +
                'the guest.')
        }
    }
    [Console]::Error.WriteLine("bombyx: $Why")
    exit 1
}

# The value of environment variable `name`, decoded from base64.
# An empty value arrives as no variable at all, because Windows
# deletes a variable set to the empty string, so a missing one
# decodes to the empty string.
function Decode([string] $Name) {
    $raw = [Environment]::GetEnvironmentVariable($Name)
    if ([string]::IsNullOrEmpty($raw)) {
        return ''
    }
    if ($raw -cnotmatch '^[A-Za-z0-9+/]*={0,2}$') {
        Refuse ("$Name is not base64. The generated Vagrantfile and " +
            'this script came from different versions of bombyx.')
    }
    return [Text.Encoding]::UTF8.GetString(
        [Convert]::FromBase64String($raw))
}

# Grants `sid`, SYSTEM and the administrators full control of
# `path`, removes every inherited entry, and makes `sid` the
# owner. The Windows counterpart of chown and mode 0600: sshd
# refuses an authorized_keys file other accounts can write.
function Protect([string] $Path, [string] $Sid) {
    $inherit = ''
    if (Test-Path -LiteralPath $Path -PathType Container) {
        $inherit = '(OI)(CI)'
    }
    $out = & icacls.exe $Path /inheritance:r /grant:r `
        "*${Sid}:${inherit}F" "*${SystemSid}:${inherit}F" `
        "*${AdministratorsSid}:${inherit}F" 2>&1
    if ($LASTEXITCODE -ne 0) {
        Refuse "could not set the permissions on ${Path}: $out"
    }
    $out = & icacls.exe $Path /setowner "*$Sid" 2>&1
    if ($LASTEXITCODE -ne 0) {
        Refuse "could not make $Path the agent's: $out"
    }
}

# Asks Windows to create the account's profile, which it otherwise
# does at the first logon. The hand-over key has to sit in the
# profile before that logon. A folder made by hand instead would
# be taken by Windows for someone else's, and the profile would
# land beside it with a suffix.
function New-Profile([string] $Sid, [string] $Name) {
    $signature = @'
[DllImport("userenv.dll", CharSet = CharSet.Unicode)]
public static extern int CreateProfile(
    string sid, string name, System.Text.StringBuilder path, uint size);
'@
    $userenv = Add-Type -MemberDefinition $signature -Name UserEnv `
        -Namespace Bombyx -PassThru
    $path = New-Object Text.StringBuilder 260
    $result = $userenv::CreateProfile($Sid, $Name, $path, 260)
    if ($result -ne 0) {
        Refuse ("Windows could not create a profile for $Name " +
            ('(CreateProfile returned 0x{0:X8}).' -f $result))
    }
}

try {
    $User = Decode 'BOMBYX_GUEST_USER'
    # The rules GuestUser applies, plus Windows' 20-character cap.
    # bombyx checked them when it read the config; checking here
    # too keeps a Vagrantfile from another version from reaching
    # New-LocalUser with a name nobody checked.
    if ($User -cnotmatch '^[a-z_][a-z0-9_-]{0,19}$') {
        Refuse "guest_user (`"$User`") is not an account name bombyx creates."
    }
    $builtIn = @('administrator', 'guest', 'defaultaccount',
        'wdagutilityaccount', 'root', 'vagrant')
    if ($builtIn -contains $User -or $User -eq $env:USERNAME) {
        Refuse ("guest_user (`"$User`") is a built-in account or the " +
            'account Vagrant logs in as. The agent needs an account ' +
            'of its own.')
    }

    $Preserve = Decode 'BOMBYX_PRESERVE_ENV'
    if ($Preserve -cnotmatch '^[A-Za-z_][A-Za-z0-9_]*(,[A-Za-z_][A-Za-z0-9_]*)*$') {
        Refuse ('BOMBYX_PRESERVE_ENV is missing or holds something ' +
            'other than variable names. The generated Vagrantfile and ' +
            'this script came from different versions of bombyx.')
    }

    $staged = Join-Path $Staging 'bootstrap.ps1'
    if (-not (Test-Path -LiteralPath $staged -PathType Leaf)) {
        Refuse ("bootstrap.ps1 did not arrive at $staged, so there " +
            "is nothing to hand to the agent's account.")
    }
    foreach ($tool in @($Ssh, $SshKeygen)) {
        if (-not (Test-Path -LiteralPath $tool -PathType Leaf)) {
            Refuse ("$tool is not on this box, and bombyx needs it to " +
                "hand over to the agent's account. Choose a box that " +
                'has the OpenSSH client.')
        }
    }

    New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
    if (Test-Path -LiteralPath $AccountRecord) {
        $recorded = (Get-Content -LiteralPath $AccountRecord -Raw).Trim()
        if ($recorded -ne $User) {
            Refuse ("this VM was set up for guest_user `"$recorded`", " +
                "and the config now names `"$User`". bombyx does not " +
                'move a VM from one account to another; run bombyx ' +
                'destroy, then bombyx up.')
        }
    }

    # The account. Its password is random and kept nowhere: the
    # agent logs in with the hand-over key alone.
    $account = Get-LocalUser -Name $User -ErrorAction SilentlyContinue
    if ($null -eq $account) {
        $bytes = New-Object byte[] 24
        [Security.Cryptography.RandomNumberGenerator]::Create().GetBytes(
            $bytes)
        # The suffix meets Windows' complexity rule whatever the
        # random part holds.
        $password = ConvertTo-SecureString -AsPlainText -Force `
            ([Convert]::ToBase64String($bytes) + 'aA1!')
        $account = New-LocalUser -Name $User -Password $password `
            -PasswordNeverExpires -AccountNeverExpires `
            -Description 'The account bombyx runs the agent as'
    }
    $sid = $account.SID.Value
    Set-Content -LiteralPath $AccountRecord -Value $User -Encoding ASCII

    # An administrator, the Windows counterpart of the Linux agent's
    # passwordless sudo: the agent installs what its build needs.
    $admins = Get-LocalGroupMember -SID $AdministratorsSid |
        Where-Object { $_.SID.Value -eq $sid }
    if ($null -eq $admins) {
        Add-LocalGroupMember -SID $AdministratorsSid -Member $sid
    }

    $profileKey = 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\' +
        "ProfileList\$sid"
    if (-not (Test-Path -LiteralPath $profileKey)) {
        New-Profile $sid $User
    }
    $AgentHome = (Get-ItemProperty -LiteralPath $profileKey).ProfileImagePath
    $expected = Join-Path (Split-Path -Parent $env:USERPROFILE) $User
    if ($AgentHome -ne $expected -or
        -not (Test-Path -LiteralPath $AgentHome -PathType Container)) {
        Refuse ("the account $User has its profile at `"$AgentHome`", " +
            "and bombyx needs it at $expected. A folder of that name " +
            'probably existed before the account did. Choose another ' +
            'guest_user, or run bombyx destroy, then bombyx up.')
    }

    # git, unless this version is already installed.
    $gitExe = Join-Path $GitDir 'cmd\git.exe'
    $versionFile = Join-Path $GitDir 'bombyx-version'
    $installed = ''
    if (Test-Path -LiteralPath $versionFile) {
        $installed = (Get-Content -LiteralPath $versionFile -Raw).Trim()
    }
    if (-not (Test-Path -LiteralPath $gitExe) -or
        $installed -ne $MinGitVersion) {
        Write-Output "bombyx: installing git $MinGitVersion"
        # Windows PowerShell 5.1 offers TLS 1.0 by default, which
        # GitHub refuses.
        [Net.ServicePointManager]::SecurityProtocol =
            [Net.SecurityProtocolType]::Tls12
        $zip = Join-Path $env:TEMP "bombyx-mingit-$MinGitVersion.zip"
        try {
            Invoke-WebRequest -UseBasicParsing -Uri $MinGitUrl `
                -OutFile $zip
        } catch {
            Refuse ("could not download git from ${MinGitUrl}: " +
                $_.Exception.Message)
        }
        $hash = (Get-FileHash -Algorithm SHA256 -LiteralPath $zip).Hash
        if ($hash -ne $MinGitSha256) {
            Remove-Item -LiteralPath $zip -Force
            Refuse ("the git download from $MinGitUrl has SHA-256 " +
                "$hash, and bombyx expects $MinGitSha256. Refusing to " +
                'install it.')
        }
        # Unpacked beside the old copy and moved into place, so a
        # failure part-way leaves the old copy or none, never half.
        $unpack = "$GitDir.new"
        if (Test-Path -LiteralPath $unpack) {
            Remove-Item -LiteralPath $unpack -Recurse -Force
        }
        Expand-Archive -LiteralPath $zip -DestinationPath $unpack
        Remove-Item -LiteralPath $zip -Force
        Set-Content -LiteralPath (Join-Path $unpack 'bombyx-version') `
            -Value $MinGitVersion -Encoding ASCII
        if (Test-Path -LiteralPath $GitDir) {
            Remove-Item -LiteralPath $GitDir -Recurse -Force
        }
        Move-Item -LiteralPath $unpack -Destination $GitDir
    }
    # On the machine's PATH, so the agent's own shells find git as a
    # Linux agent does. bootstrap.ps1 does not rely on it.
    $gitCmd = Join-Path $GitDir 'cmd'
    $machinePath = [Environment]::GetEnvironmentVariable('Path', 'Machine')
    if (($machinePath -split ';') -notcontains $gitCmd) {
        [Environment]::SetEnvironmentVariable(
            'Path', "$machinePath;$gitCmd", 'Machine')
    }

    # bootstrap.ps1, installed afresh on every provision so the
    # agent's own edits to an earlier copy never run.
    Copy-Item -LiteralPath $staged -Destination $Bootstrap -Force
    Remove-Item -LiteralPath $Staging -Recurse -Force

    # The hand-over key, made once and kept, so a later provision
    # finds the same key authorized.
    New-Item -ItemType Directory -Force -Path $LoginSsh | Out-Null
    if (-not (Test-Path -LiteralPath $HandoverKey)) {
        # Start-Process takes the command line as written, so the
        # empty passphrase reaches ssh-keygen as `""`, which it reads
        # as empty. Passed through `&`, the quoting would depend on
        # the PowerShell version.
        $keygen = Start-Process -FilePath $SshKeygen -Wait -PassThru `
            -NoNewWindow -ArgumentList ('-q -t ed25519 -N "" ' +
                "-C bombyx-handover -f `"$HandoverKey`"")
        if ($keygen.ExitCode -ne 0) {
            Refuse "could not make the hand-over key at $HandoverKey."
        }
    }
    $public = (Get-Content -LiteralPath "$HandoverKey.pub" -Raw).Trim()

    # Authorized in the agent's own .ssh. sshd reads that file for
    # an administrator too on this box, because its sshd_config
    # leaves the administrators_authorized_keys block commented out.
    $agentSsh = Join-Path $AgentHome '.ssh'
    New-Item -ItemType Directory -Force -Path $agentSsh | Out-Null
    Protect $agentSsh $sid
    $authorized = Join-Path $agentSsh 'authorized_keys'
    $lines = @()
    if (Test-Path -LiteralPath $authorized) {
        $lines = @(Get-Content -LiteralPath $authorized)
    }
    if ($lines -notcontains $public) {
        Set-Content -LiteralPath $authorized -Value ($lines + $public) `
            -Encoding ASCII
    }
    Protect $authorized $sid

    # The guest's own host key, so the login checks it strictly
    # rather than trusting whatever answers on localhost.
    $hostKey = Join-Path $env:ProgramData 'ssh\ssh_host_ed25519_key.pub'
    if (-not (Test-Path -LiteralPath $hostKey)) {
        Refuse ("sshd's host key is not at $hostKey, so bombyx cannot " +
            'check the login it hands over through.')
    }
    $parts = (Get-Content -LiteralPath $hostKey -Raw).Trim() -split '\s+'
    Set-Content -LiteralPath $LocalKnownHosts -Encoding ASCII `
        -Value "localhost $($parts[0]) $($parts[1])"

    # An unactivated evaluation shuts down 10 days after its first
    # boot. bombyx does not activate it, because activating contacts
    # Microsoft; it says how long is left. The ID is Windows' own
    # application ID in the licensing service.
    try {
        $licence = Get-CimInstance -ClassName SoftwareLicensingProduct `
            -Filter ("ApplicationID='55c92734-d682-4d71-983e-d6ec3f16059f'" +
                ' AND PartialProductKey IS NOT NULL') |
            Select-Object -First 1
        if ($null -ne $licence -and $licence.LicenseStatus -ne 1) {
            $days = [math]::Floor($licence.GracePeriodRemaining / 1440)
            Write-Output ("bombyx: this Windows evaluation is not " +
                "activated and shuts down in about $days days unless it " +
                'is. To activate it, run in the guest: cscript //nologo ' +
                'C:\Windows\System32\slmgr.vbs /ato')
        }
    } catch {
        Write-Output ('bombyx: could not read whether Windows is ' +
            'activated. An unactivated evaluation shuts down 10 days ' +
            'after its first boot.')
    }

    # The script the login runs: each preserved variable set from
    # its base64, then bootstrap.ps1. The names matched the pattern
    # above and each value is base64 checked by Decode's pattern, so
    # neither can close the quotes it is pasted into. Written to the
    # agent's home, protected before it holds anything.
    $handover = Join-Path $AgentHome '.bombyx-handover.ps1'
    Set-Content -LiteralPath $handover -Value '' -Encoding ASCII
    Protect $handover $sid
    $body = New-Object Text.StringBuilder
    foreach ($name in $Preserve -split ',') {
        $raw = [Environment]::GetEnvironmentVariable($name)
        if ($null -eq $raw) {
            $raw = ''
        }
        if ($raw -cnotmatch '^[A-Za-z0-9+/]*={0,2}$') {
            Refuse ("$name is not base64. The generated Vagrantfile " +
                'and this script came from different versions of bombyx.')
        }
        [void]$body.AppendLine(
            "`$env:$name = [Text.Encoding]::UTF8.GetString(" +
            "[Convert]::FromBase64String('$raw'))")
    }
    [void]$body.AppendLine(
        "& '$($Bootstrap -replace "'", "''")'")
    [void]$body.AppendLine('exit $LASTEXITCODE')
    Set-Content -LiteralPath $handover -Value $body.ToString() `
        -Encoding ASCII

    # The hand-over. BatchMode keeps ssh from asking for anything,
    # -n gives it no stdin, and -T asks for no terminal. The remote
    # command reaches cmd.exe, sshd's default shell here, and holds
    # no character cmd.exe reads.
    #
    # ssh's stderr is not redirected: with `2>&1`, Windows' ssh
    # client and PowerShell 5.1 stop after the first line of output
    # and never return, whatever the remote side runs. Unredirected,
    # its output passes straight through, and 'Continue' keeps any
    # stderr PowerShell does see from ending this script.
    $ErrorActionPreference = 'Continue'
    & $Ssh -n -T -i $HandoverKey -o IdentitiesOnly=yes `
        -o BatchMode=yes -o StrictHostKeyChecking=yes `
        -o "UserKnownHostsFile=$LocalKnownHosts" `
        "$User@localhost" powershell.exe -NoProfile -NonInteractive `
        -ExecutionPolicy Bypass -File $handover
    $code = $LASTEXITCODE
    $ErrorActionPreference = 'Stop'
    if ($code -eq 255) {
        [Console]::Error.WriteLine(
            "bombyx: the SSH login to $User@localhost failed, so " +
            "bootstrap.ps1 did not run as $User. If this box's " +
            'sshd_config enables the administrators_authorized_keys ' +
            "block, sshd ignores $authorized for an administrator.")
    }
    exit $code
} catch {
    Refuse ('the account setup stopped on an unexpected error: ' +
        $_.Exception.Message)
}
