# Generated by bombyx. Do not edit: bombyx rewrites it on every
# `up`, `provision` and `scratch`.
#
# Clones the project and runs its script, as the agent, on a
# Windows guest. account.ps1 installs this file and runs it over an
# SSH login as the agent, after setting the variables below from
# their base64. It is not meant to be run by hand.
#
# Targets Windows PowerShell 5.1, which is what the box ships.

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'
Set-StrictMode -Version 2.0

# The credentials account.ps1 placed, set once the agent's profile is
# known. Refuse removes them, as bootstrap.sh does, so a refused
# provision leaves no credential behind.
$Secrets = @()

# Prints `why` to stderr with bombyx's prefix, removes the placed
# credentials, and exits 1.
function Refuse([string] $Why) {
    foreach ($path in $Secrets) {
        Remove-Item -LiteralPath $path -Force -ErrorAction SilentlyContinue
    }
    [Console]::Error.WriteLine("bombyx: $Why")
    $left = @($Secrets | Where-Object { Test-Path -LiteralPath $_ })
    if ($left.Count -gt 0) {
        [Console]::Error.WriteLine(
            "bombyx: A CREDENTIAL IS STILL IN THIS GUEST, at " +
            "$($left -join ', '), because it could not be removed. " +
            'Remove it in the guest.')
    } elseif ($Secrets.Count -gt 0) {
        [Console]::Error.WriteLine(
            'bombyx: any deploy key, secrets file and git credential ' +
            'have been removed from this guest.')
    }
    exit 1
}

# The reason given when the Vagrantfile and this script disagree.
$VersionSkew = 'The generated Vagrantfile and this script came from ' +
    'different versions of bombyx.'

# The value of environment variable `name`, refusing when it is
# unset or empty.
function Need([string] $Name) {
    $value = [Environment]::GetEnvironmentVariable($Name)
    if ([string]::IsNullOrEmpty($value)) {
        Refuse ("$Name is not set. account.ps1 hands it over; run the " +
            'bombyx command rather than this script.')
    }
    return $value
}

# Runs a native command, printing its stderr as plain lines on
# stdout, and leaves its exit code in $LASTEXITCODE. Windows
# PowerShell 5.1 turns a native command's stderr into error
# records once its output is redirected, as it is under SSH, and
# 'Stop' would make the first one, such as git's progress, end the
# script. So the command runs under 'Continue' here.
function Invoke-Native {
    $ErrorActionPreference = 'Continue'
    $command = $args[0]
    $rest = @($args | Select-Object -Skip 1)
    # A stderr line arrives as an error record holding the line as
    # its TargetObject. Its own text falls back to the type name
    # for an empty line, so the line is printed from TargetObject.
    & $command @rest 2>&1 | ForEach-Object {
        if ($_ -is [Management.Automation.ErrorRecord]) {
            "$($_.TargetObject)"
        } else {
            "$_"
        }
    }
}

# Whether two remote URLs name the same repository, ignoring one
# trailing slash and then one `.git`, as bootstrap.sh does.
function Test-SameRepo([string] $A, [string] $B) {
    $trimmed = foreach ($url in @($A, $B)) {
        if ($url.EndsWith('/')) {
            $url = $url.Substring(0, $url.Length - 1)
        }
        if ($url.EndsWith('.git')) {
            $url = $url.Substring(0, $url.Length - 4)
        }
        $url
    }
    return $trimmed[0] -ceq $trimmed[1]
}

# Whether the clone at `dir` holds only part of its history, as
# bootstrap.sh's clone_is_shallow decides: a clone git cannot answer
# for counts as full, so a later fetch does not cut it.
function Test-CloneIsShallow([string] $Git, [string] $Dir) {
    $answer = & {
        $ErrorActionPreference = 'Continue'
        & $Git -C $Dir rev-parse --is-shallow-repository 2>$null
    }
    return "$answer" -eq 'true'
}

# Whether the clone at `dir` may hold work the agent has not
# committed, as bootstrap.sh's clone_may_hold_work decides: an edited
# tracked file or an untracked one, with the executable bit ignored,
# and a status git cannot give counted as work.
function Test-CloneHoldsWork([string] $Git, [string] $Dir) {
    $status = & {
        $ErrorActionPreference = 'Continue'
        & $Git -C $Dir -c core.fileMode=false status --porcelain 2>$null
    }
    if ($LASTEXITCODE -ne 0) {
        return $true
    }
    return (@($status) -join '') -ne ''
}

# Changes `key` in the git config of the clone at `dir`: 'replace'
# makes `value` its only value, 'add' appends `value`, and 'unset'
# removes every value, succeeding when there was none, which git
# reports with exit code 5. Refuses when git fails.
function Set-CloneConfig([string] $Git, [string] $Dir, [string] $Mode,
        [string] $Key, [string] $Value) {
    switch ($Mode) {
        'replace' {
            Invoke-Native $Git -C $Dir config --replace-all $Key $Value
        }
        'add' { Invoke-Native $Git -C $Dir config --add $Key $Value }
        'unset' { Invoke-Native $Git -C $Dir config --unset-all $Key }
        default { Refuse "Set-CloneConfig has no mode `"$Mode`"." }
    }
    if (-not ($LASTEXITCODE -eq 0 -or
            ($Mode -eq 'unset' -and $LASTEXITCODE -eq 5))) {
        Refuse "could not set $Key in the clone's git config."
    }
}

try {
    $Repo = Need 'BOMBYX_REPO'
    $Ref = Need 'BOMBYX_REF'
    $Script = Need 'BOMBYX_SCRIPT'
    $User = Need 'BOMBYX_GUEST_USER'
    # The Vagrantfile always sets BOMBYX_PROJECT; the fallback mirrors
    # bootstrap.sh's, where it keeps `set -u` from aborting, and gives
    # a hand run of this script a folder name.
    $Project = $env:BOMBYX_PROJECT
    if ([string]::IsNullOrEmpty($Project)) {
        $Project = 'project'
    }

    if ($User -cnotmatch '^[a-z_][a-z0-9_-]{0,19}$') {
        Refuse ("BOMBYX_GUEST_USER is `"$User`", which is not an account " +
            "name bombyx creates. $VersionSkew")
    }
    if ($env:USERNAME -ne $User) {
        Refuse ("this script runs as $env:USERNAME, and bombyx set up " +
            "$User for the agent. account.ps1 hands it over; run the " +
            'bombyx command rather than this script.')
    }
    $AgentHome = $env:USERPROFILE
    if ([string]::IsNullOrEmpty($AgentHome) -or
        -not [IO.Path]::IsPathRooted($AgentHome) -or
        -not (Test-Path -LiteralPath $AgentHome -PathType Container)) {
        Refuse ("USERPROFILE is `"$AgentHome`", which is not a folder " +
            'bombyx can clone into.')
    }
    $CloneDir = Join-Path $AgentHome $Project

    # The credentials account.ps1 placed, at the paths bootstrap.sh
    # uses in a Linux agent's home.
    $DeployKey = Join-Path $AgentHome '.ssh\bombyx-deploy-key'
    $EnvFile = Join-Path $AgentHome '.bombyx-env'
    $GitCred = Join-Path $AgentHome '.bombyx-git-credentials'
    $Secrets = @($DeployKey, $EnvFile, $GitCred)
    # A configured file must have arrived. One the config no longer
    # names is removed, so a credential nobody granted does not stay.
    # bombyx stages all three for its own vagrant run alone.
    $rerunAdvice = 'bombyx stages it only for the length of its own ' +
        'vagrant run, so a vagrant provision started by hand on the VM ' +
        'host does not find it. Re-run the bombyx command instead.'
    foreach ($item in @(
            @('BOMBYX_DEPLOY_KEY', $DeployKey, 'deploy key', $rerunAdvice),
            @('BOMBYX_ENV_FILE_PRESENT', $EnvFile, 'env_file', $rerunAdvice),
            @('BOMBYX_GIT_CRED_PRESENT', $GitCred,
                "git credential for repo_token", $rerunAdvice))) {
        $name, $file, $what, $fix = $item
        if ([Environment]::GetEnvironmentVariable($name) -eq '1') {
            if (-not (Test-Path -LiteralPath $file -PathType Leaf)) {
                Refuse "the configured $what did not arrive at $file. $fix"
            }
        } else {
            Remove-Item -LiteralPath $file -Force -ErrorAction SilentlyContinue
            if (Test-Path -LiteralPath $file) {
                Refuse ("the config names no $what, and the copy at $file " +
                    'could not be removed. Remove it in the guest: a ' +
                    'credential nobody granted is still in this VM.')
            }
        }
    }
    # The project's script finds its secrets through this, as on
    # Linux. Windows deletes a variable set to the empty string, so
    # with no env_file the script finds it unset.
    if ($env:BOMBYX_ENV_FILE_PRESENT -eq '1') {
        $env:BOMBYX_ENV_FILE = $EnvFile
    } else {
        $env:BOMBYX_ENV_FILE = ''
    }

    $Git = Join-Path $env:ProgramFiles 'bombyx\git\cmd\git.exe'
    if (-not (Test-Path -LiteralPath $Git -PathType Leaf)) {
        Refuse ("git is not at $Git. account.ps1 installs it; run the " +
            'bombyx command rather than this script.')
    }
    $env:Path = "$(Split-Path -Parent $Git);$env:Path"

    # The git host's ssh keys, fetched over HTTPS when bombyx knows
    # where the host publishes them, so the clone can tell the host
    # from an impostor. Over HTTPS only, and no redirect is followed:
    # stricter than bootstrap.sh's curl, which follows an https one,
    # and neither published URL redirects.
    $sshDir = Join-Path $AgentHome '.ssh'
    $KnownHosts = Join-Path $sshDir 'bombyx-known-hosts'
    # An empty file, standing in for ssh's own config and global
    # known_hosts, so neither can choose another identity or host key.
    $EmptyFile = Join-Path $sshDir 'bombyx-empty'
    New-Item -ItemType Directory -Force -Path $sshDir | Out-Null
    [IO.File]::WriteAllText($EmptyFile, '')
    $gitHost = [string]$env:BOMBYX_GIT_HOST
    $keysUrl = [string]$env:BOMBYX_HOST_KEYS_URL
    $keysFormat = [string]$env:BOMBYX_HOST_KEYS_FORMAT
    if ($keysUrl -ne '') {
        if ($gitHost -eq '' -or -not $keysUrl.StartsWith('https://')) {
            Refuse ('bombyx published a key URL it cannot use: host ' +
                "`"$gitHost`", URL `"$keysUrl`". $VersionSkew")
        }
        [Net.ServicePointManager]::SecurityProtocol =
            [Net.SecurityProtocolType]::Tls12
        try {
            $response = Invoke-WebRequest -UseBasicParsing -Uri $keysUrl `
                -MaximumRedirection 0 -TimeoutSec 30
        } catch {
            Refuse ("bombyx could not read $gitHost's ssh host keys from " +
                "${keysUrl}: $($_.Exception.Message) Without them the " +
                'guest cannot tell that host from an impostor, so it will ' +
                'not clone.')
        }
        switch ($keysFormat) {
            'json' {
                $lines = @(($response.Content | ConvertFrom-Json).ssh_keys |
                    ForEach-Object { "$gitHost $_" })
            }
            'lines' {
                $lines = @($response.Content -split "`r?`n" |
                    Where-Object { $_ -ne '' })
            }
            default {
                Refuse ("bombyx asked for $gitHost's ssh host keys in a " +
                    "format this script does not know: `"$keysFormat`". " +
                    $VersionSkew)
            }
        }
        if (-not ($lines | Where-Object { $_.StartsWith("$gitHost ") })) {
            Refuse ("the keys bombyx fetched from $keysUrl hold no line " +
                "for $gitHost, so there is nothing to verify that host " +
                'against. Check whether that URL still publishes host keys.')
        }
        Set-Content -LiteralPath $KnownHosts -Value $lines -Encoding ASCII
    }

    # The ssh command git uses: the client MinGit carries, not
    # Windows' own. Driven by git over pipes from this session, which
    # has no console, Windows' ssh.exe authenticates, sends
    # git-upload-pack and then moves no data, so a clone hangs; MinGit's
    # completes. Forward slashes, because git runs the command through
    # its own sh. The program's path holds a space, escaped with a
    # backslash as sh reads it rather than quoted: Windows PowerShell
    # 5.1 passes an argument holding double quotes to a native program
    # without escaping them, so a quoted path would reach `git config`
    # split. The agent's paths hold no space, because its name has none.
    $toSlash = { param($path) $path -replace '\\', '/' }
    $gitRoot = Split-Path -Parent (Split-Path -Parent $Git)
    $sshPath = Join-Path $gitRoot 'usr\bin\ssh.exe'
    if (-not (Test-Path -LiteralPath $sshPath -PathType Leaf)) {
        Refuse ("git's ssh client is not at $sshPath. account.ps1 installs " +
            'it with git; run the bombyx command rather than this script.')
    }
    $gitSsh = (& $toSlash $sshPath) -replace ' ', '\ '
    if ($env:BOMBYX_DEPLOY_KEY -eq '1') {
        $gitSsh += " -F $(& $toSlash $EmptyFile)" +
            " -i $(& $toSlash $DeployKey) -o IdentitiesOnly=yes"
    }
    if ($keysUrl -ne '') {
        $gitSsh += ' -o StrictHostKeyChecking=yes' +
            " -o UserKnownHostsFile=$(& $toSlash $KnownHosts)" +
            " -o GlobalKnownHostsFile=$(& $toSlash $EmptyFile)"
    } elseif ($env:BOMBYX_DEPLOY_KEY -eq '1') {
        # A key and no published key source: `accept-new` records the
        # host on first sight and refuses a change afterwards. With
        # neither, ssh keeps its default, as in bootstrap.sh: such a
        # clone has no credential either, so it could not authenticate
        # whatever this said.
        $gitSsh += ' -o StrictHostKeyChecking=accept-new'
    }
    # For bombyx's own git calls only: BatchMode makes ssh fail rather
    # than wait for an answer nobody can give. The clone records
    # $gitSsh without it, below.
    $env:GIT_SSH_COMMAND = "$gitSsh -o BatchMode=yes"

    # The credential helper for a repo_token. The empty entry first
    # clears any helper git's own config names, so only this file
    # answers.
    $gitNet = @()
    $credHelper = ''
    if ($env:BOMBYX_GIT_CRED_PRESENT -eq '1') {
        $credHelper = "store --file=$(& $toSlash $GitCred)"
        $gitNet = @('-c', 'credential.helper=', '-c',
            "credential.helper=$credHelper")
    }

    # How this provision may update the clone, falling back to the
    # mode that refuses to overwrite the agent's work. Checked once
    # the credentials are known, so a refusal removes them;
    # bootstrap.sh says why each part is there.
    $CloneUpdate = $env:BOMBYX_CLONE_UPDATE
    if ([string]::IsNullOrEmpty($CloneUpdate)) {
        $CloneUpdate = 'checkout'
    }
    if ($CloneUpdate -cnotin @('checkout', 'discard', 'keep')) {
        Refuse ("BOMBYX_CLONE_UPDATE is `"$CloneUpdate`", which this " +
            'script does not know. The shell that ran vagrant on the VM ' +
            'host set it; unset it there, or run bombyx provision.')
    }
    # How much of the repository the clone holds, from
    # [source].history; bootstrap.sh says why each part is there.
    $History = $env:BOMBYX_HISTORY
    if ([string]::IsNullOrEmpty($History)) {
        $History = 'full'
    }
    if ($History -cnotin @('full', 'shallow')) {
        Refuse ("BOMBYX_HISTORY is `"$History`", which this script does " +
            'not know. Set source.history to full or shallow, then ' +
            'provision again.')
    }

    if (Test-Path -LiteralPath (Join-Path $CloneDir '.git') -PathType Container) {
        $origin = & {
            $ErrorActionPreference = 'Continue'
            & $Git -C $CloneDir remote get-url origin 2>$null
        }
        if ($LASTEXITCODE -eq 0 -and -not (Test-SameRepo "$origin" $Repo)) {
            if ($CloneUpdate -eq 'keep') {
                Refuse ("this VM holds a clone of $origin but the config " +
                    "asks for $Repo, so --no-fetch has no script of that " +
                    'repository to run. Provision without it.')
            }
            if ($CloneUpdate -ne 'discard' -and
                (Test-CloneHoldsWork $Git $CloneDir)) {
                Refuse ("this VM holds a clone of $origin with uncommitted " +
                    "work in it, and the config now asks for $Repo, so the " +
                    'clone would be deleted. Push the work from the guest, ' +
                    "or run bombyx provision --discard to delete it: $CloneDir")
            }
            [Console]::Error.WriteLine(
                "bombyx: this VM holds a clone of $origin but " +
                "the config asks for $Repo.")
            [Console]::Error.WriteLine(
                'bombyx: discarding the clone and starting again. ' +
                "Uncommitted work in $CloneDir is lost.")
            Remove-Item -LiteralPath $CloneDir -Recurse -Force `
                -ErrorAction SilentlyContinue
            if (Test-Path -LiteralPath $CloneDir) {
                Refuse ('could not remove the clone. Clear it in the ' +
                    "guest, then provision again: $CloneDir")
            }
        }
    }

    if (Test-Path -LiteralPath (Join-Path $CloneDir '.git') -PathType Container) {
        if ($CloneUpdate -eq 'keep') {
            $head = & {
                $ErrorActionPreference = 'Continue'
                & $Git -C $CloneDir rev-parse --short HEAD 2>$null
            }
            if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrEmpty("$head")) {
                $head = 'an unreadable HEAD'
            }
            [Console]::Error.WriteLine(
                'bombyx: not updating the clone (--no-fetch); running ' +
                "from commit $head.")
            if (Test-CloneHoldsWork $Git $CloneDir) {
                [Console]::Error.WriteLine(
                    'bombyx: the clone holds uncommitted work, which the ' +
                    'script sees as it is.')
            }
        } else {
            $updateFailed = 'could not update the clone. The message ' +
                'above says why. If something in it belongs to another ' +
                "user, clear it in the guest: $CloneDir"
            # Every branch under full history, unshallowing a clone an
            # earlier provision left shallow; bootstrap.sh says why
            # each fetch is needed.
            if ($History -eq 'full') {
                Invoke-Native $Git -C $CloneDir remote set-branches origin '*'
                if ($LASTEXITCODE -ne 0) {
                    Refuse $updateFailed
                }
                if (Test-CloneIsShallow $Git $CloneDir) {
                    Invoke-Native $Git @gitNet -C $CloneDir fetch `
                        --unshallow origin
                } else {
                    Invoke-Native $Git @gitNet -C $CloneDir fetch origin
                }
                if ($LASTEXITCODE -ne 0) {
                    Refuse $updateFailed
                }
            }
            # A depth only for a clone that is shallow already, so a
            # full clone keeps its history under shallow.
            if ($History -eq 'shallow' -and
                (Test-CloneIsShallow $Git $CloneDir)) {
                Invoke-Native $Git @gitNet -C $CloneDir fetch --depth 1 origin `
                    '--' $Ref
            } else {
                Invoke-Native $Git @gitNet -C $CloneDir fetch origin '--' $Ref
            }
            if ($LASTEXITCODE -ne 0) {
                Refuse $updateFailed
            }
            # Only --discard forces the checkout; bootstrap.sh says what
            # a plain one refuses. core.fileMode=false matters there
            # because that script runs chmod +x on the project's script;
            # nothing here sets the bit, so on Windows it only keeps the
            # two scripts' git calls the same.
            if ($CloneUpdate -eq 'discard') {
                Invoke-Native $Git -C $CloneDir checkout --force FETCH_HEAD
                if ($LASTEXITCODE -ne 0) {
                    Refuse ('could not update the clone. The message above ' +
                        'says why, and the checkout may be half-changed. ' +
                        "Clear it in the guest: $CloneDir")
                }
            } else {
                Invoke-Native $Git -C $CloneDir -c core.fileMode=false `
                    checkout FETCH_HEAD
                if ($LASTEXITCODE -ne 0) {
                    Refuse ('did not update the clone. The message ' +
                        'above says why. When it lists files, they hold ' +
                        "the agent's work: push or stash it in the guest, " +
                        'or run bombyx provision --discard to overwrite ' +
                        'it. When something belongs to another user, ' +
                        "clear it in the guest: $CloneDir")
                }
            }
        }
    } else {
        if ($CloneUpdate -eq 'keep') {
            Refuse ('--no-fetch runs the script from the clone, and this ' +
                "VM has none at $CloneDir. Provision without it to make one.")
        }
        if ((Test-Path -LiteralPath $CloneDir) -and
            $null -ne (Get-ChildItem -LiteralPath $CloneDir -Force |
                Select-Object -First 1)) {
            Refuse ("$CloneDir is not empty and holds no checkout, so it " +
                'is a leftover. Remove it in the guest, then provision ' +
                'again.')
        }
        # Without --depth, git writes its default refspec, which
        # fetches every branch.
        if ($History -eq 'full') {
            $depth = @()
        } else {
            $depth = @('--depth', '1')
        }
        Invoke-Native $Git @gitNet clone @depth --branch $Ref '--' $Repo `
            $CloneDir
        if ($LASTEXITCODE -ne 0) {
            Refuse ("could not clone $Repo. The message above says why.")
        }
    }

    # The clone's own config carries the ssh command and the helper,
    # so the agent's later fetches and pushes use the same key and
    # credential. Unset when neither applies, so a config that dropped
    # one leaves the clone without it.
    if ($env:BOMBYX_DEPLOY_KEY -eq '1' -or $keysUrl -ne '') {
        Set-CloneConfig $Git $CloneDir 'replace' 'core.sshCommand' $gitSsh
    } else {
        Set-CloneConfig $Git $CloneDir 'unset' 'core.sshCommand'
    }
    # The helper list starts with an empty entry, which clears any
    # helper git's own config names, as the `-c` pair does for bombyx's
    # calls above, so only the credential file answers the agent's
    # later fetches and pushes.
    Set-CloneConfig $Git $CloneDir 'unset' 'credential.helper'
    if ($credHelper -ne '') {
        # The empty entry is passed as the two characters `""`.
        # Windows PowerShell 5.1 drops an empty-string argument to a
        # native program, but passes `""` on the command line as an
        # empty quoted argument, which git reads as empty.
        Set-CloneConfig $Git $CloneDir 'add' 'credential.helper' '""'
        Set-CloneConfig $Git $CloneDir 'add' 'credential.helper' $credHelper
    }
    Remove-Item -LiteralPath Env:GIT_SSH_COMMAND -ErrorAction SilentlyContinue

    # The script, which has to be a .ps1 file inside the clone with
    # no link on the way to it. A link could point anywhere on the
    # guest, and bombyx runs only what the project's own tree holds.
    Set-Location -LiteralPath $CloneDir
    $path = Join-Path $CloneDir $Script
    if (-not (Test-Path -LiteralPath $path)) {
        Refuse ("$Script is not in the cloned project. Check the " +
            '`script` key in your config.')
    }
    $full = [IO.Path]::GetFullPath($path)
    $root = [IO.Path]::GetFullPath($CloneDir).TrimEnd('\') + '\'
    if (-not $full.StartsWith($root, [StringComparison]::OrdinalIgnoreCase)) {
        Refuse "$Script points outside the cloned project; refusing to run it."
    }
    if (-not (Test-Path -LiteralPath $full -PathType Leaf)) {
        Refuse "$Script is not a regular file."
    }
    # `-ne` ignores case, as `ScriptPath::is_powershell` does, so
    # `Setup.PS1` passes.
    if ([IO.Path]::GetExtension($full) -ne '.ps1') {
        Refuse ("$Script is not a .ps1 file, and a Windows guest runs " +
            'the script with PowerShell.')
    }
    # Every step from the script up to the clone, the script
    # included. The clone folder itself is not checked: its path is
    # one character shorter than $root, and it is the folder this
    # script cloned into, under the agent's own profile.
    $step = $full
    while ($step.Length -ge $root.Length) {
        $item = Get-Item -LiteralPath $step -Force
        if ($item.Attributes -band [IO.FileAttributes]::ReparsePoint) {
            Refuse ("$Script passes through a link at $step; refusing " +
                'to run it.')
        }
        $step = Split-Path -Parent $step
    }

    Invoke-Native powershell.exe -NoProfile -NonInteractive `
        -ExecutionPolicy Bypass -File $full
    exit $LASTEXITCODE
} catch {
    Refuse ('the bootstrap stopped on an unexpected error: ' +
        $_.Exception.Message)
}
