# Generated by bombyx. Do not edit: bombyx rewrites it on every
# `up`, `provision` and `scratch`.
#
# Clones the project and runs its script, as the agent, on a
# Windows guest. account.ps1 installs this file and runs it over an
# SSH login as the agent, after setting the variables below from
# their base64. It is not meant to be run by hand.
#
# Targets Windows PowerShell 5.1, which is what the box ships.

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'
Set-StrictMode -Version 2.0

# Prints `why` to stderr with bombyx's prefix and exits 1.
function Refuse([string] $Why) {
    [Console]::Error.WriteLine("bombyx: $Why")
    exit 1
}

# The value of environment variable `name`, refusing when it is
# unset or empty.
function Need([string] $Name) {
    $value = [Environment]::GetEnvironmentVariable($Name)
    if ([string]::IsNullOrEmpty($value)) {
        Refuse ("$Name is not set. account.ps1 hands it over; run the " +
            'bombyx command rather than this script.')
    }
    return $value
}

# Runs a native command, printing its stderr as plain lines on
# stdout, and leaves its exit code in $LASTEXITCODE. Windows
# PowerShell 5.1 turns a native command's stderr into error
# records once its output is redirected, as it is under SSH, and
# 'Stop' would make the first one, such as git's progress, end the
# script. So the command runs under 'Continue' here.
function Invoke-Native {
    $ErrorActionPreference = 'Continue'
    $command = $args[0]
    $rest = @($args | Select-Object -Skip 1)
    # A stderr line arrives as an error record holding the line as
    # its TargetObject. Its own text falls back to the type name
    # for an empty line, so the line is printed from TargetObject.
    & $command @rest 2>&1 | ForEach-Object {
        if ($_ -is [Management.Automation.ErrorRecord]) {
            "$($_.TargetObject)"
        } else {
            "$_"
        }
    }
}

# Whether two remote URLs name the same repository, ignoring one
# trailing slash and then one `.git`, as bootstrap.sh does.
function Test-SameRepo([string] $A, [string] $B) {
    $trimmed = foreach ($url in @($A, $B)) {
        if ($url.EndsWith('/')) {
            $url = $url.Substring(0, $url.Length - 1)
        }
        if ($url.EndsWith('.git')) {
            $url = $url.Substring(0, $url.Length - 4)
        }
        $url
    }
    return $trimmed[0] -ceq $trimmed[1]
}

try {
    $Repo = Need 'BOMBYX_REPO'
    $Ref = Need 'BOMBYX_REF'
    $Script = Need 'BOMBYX_SCRIPT'
    $User = Need 'BOMBYX_GUEST_USER'
    $Project = $env:BOMBYX_PROJECT
    if ([string]::IsNullOrEmpty($Project)) {
        $Project = 'project'
    }

    if ($User -cnotmatch '^[a-z_][a-z0-9_-]{0,19}$') {
        Refuse ("BOMBYX_GUEST_USER is `"$User`", which is not an account " +
            'name bombyx creates. The generated Vagrantfile and this ' +
            'script came from different versions of bombyx.')
    }
    if ($env:USERNAME -ne $User) {
        Refuse ("this script runs as $env:USERNAME, and bombyx set up " +
            "$User for the agent. account.ps1 hands it over; run the " +
            'bombyx command rather than this script.')
    }
    $AgentHome = $env:USERPROFILE
    if ([string]::IsNullOrEmpty($AgentHome) -or
        -not [IO.Path]::IsPathRooted($AgentHome) -or
        -not (Test-Path -LiteralPath $AgentHome -PathType Container)) {
        Refuse ("USERPROFILE is `"$AgentHome`", which is not a folder " +
            'bombyx can clone into.')
    }
    $CloneDir = Join-Path $AgentHome $Project

    $Git = Join-Path $env:ProgramFiles 'bombyx\git\cmd\git.exe'
    if (-not (Test-Path -LiteralPath $Git -PathType Leaf)) {
        Refuse ("git is not at $Git. account.ps1 installs it; run the " +
            'bombyx command rather than this script.')
    }
    $env:Path = "$(Split-Path -Parent $Git);$env:Path"
    # Windows' own ssh client for an ssh URL, rather than the one
    # MinGit carries. BatchMode makes it fail rather than wait for
    # an answer nobody can give. git runs the command through its
    # own sh, which reads forward slashes.
    $sshExe = (Join-Path $env:SystemRoot 'System32\OpenSSH\ssh.exe') -replace '\\', '/'
    $env:GIT_SSH_COMMAND = "`"$sshExe`" -o BatchMode=yes"

    if (Test-Path -LiteralPath (Join-Path $CloneDir '.git') -PathType Container) {
        $origin = & {
            $ErrorActionPreference = 'Continue'
            & $Git -C $CloneDir remote get-url origin 2>$null
        }
        if ($LASTEXITCODE -eq 0 -and -not (Test-SameRepo "$origin" $Repo)) {
            [Console]::Error.WriteLine(
                "bombyx: this VM holds a clone of $origin but " +
                "the config asks for $Repo.")
            [Console]::Error.WriteLine(
                'bombyx: discarding the clone and starting again. ' +
                "Uncommitted work in $CloneDir is lost.")
            Remove-Item -LiteralPath $CloneDir -Recurse -Force `
                -ErrorAction SilentlyContinue
            if (Test-Path -LiteralPath $CloneDir) {
                Refuse ('could not remove the clone. Clear it in the ' +
                    "guest, then provision again: $CloneDir")
            }
        }
    }

    if (Test-Path -LiteralPath (Join-Path $CloneDir '.git') -PathType Container) {
        Invoke-Native $Git -C $CloneDir fetch --depth 1 origin '--' $Ref
        if ($LASTEXITCODE -ne 0) {
            Refuse ('could not update the clone. The message above says ' +
                "why. If something in it belongs to another user, clear " +
                "it in the guest: $CloneDir")
        }
        Invoke-Native $Git -C $CloneDir checkout --force FETCH_HEAD
        if ($LASTEXITCODE -ne 0) {
            Refuse ('could not update the clone. The message above says ' +
                'why, and the checkout may be half-changed. Clear it in ' +
                "the guest: $CloneDir")
        }
    } else {
        if ((Test-Path -LiteralPath $CloneDir) -and
            $null -ne (Get-ChildItem -LiteralPath $CloneDir -Force |
                Select-Object -First 1)) {
            Refuse ("$CloneDir is not empty and holds no checkout, so it " +
                'is a leftover. Remove it in the guest, then provision ' +
                'again.')
        }
        Invoke-Native $Git clone --depth 1 --branch $Ref '--' $Repo $CloneDir
        if ($LASTEXITCODE -ne 0) {
            Refuse ("could not clone $Repo. The message above says why.")
        }
    }

    # The script, which has to be a .ps1 file inside the clone with
    # no link on the way to it. A link could point anywhere on the
    # guest, and bombyx runs only what the project's own tree holds.
    Set-Location -LiteralPath $CloneDir
    $path = Join-Path $CloneDir $Script
    if (-not (Test-Path -LiteralPath $path)) {
        Refuse ("$Script is not in the cloned project. Check the " +
            '`script` key in your config.')
    }
    $full = [IO.Path]::GetFullPath($path)
    $root = [IO.Path]::GetFullPath($CloneDir).TrimEnd('\') + '\'
    if (-not $full.StartsWith($root, [StringComparison]::OrdinalIgnoreCase)) {
        Refuse "$Script points outside the cloned project; refusing to run it."
    }
    if (-not (Test-Path -LiteralPath $full -PathType Leaf)) {
        Refuse "$Script is not a regular file."
    }
    if ([IO.Path]::GetExtension($full) -ne '.ps1') {
        Refuse ("$Script is not a .ps1 file, and a Windows guest runs " +
            'the script with PowerShell.')
    }
    # Every step from the script up to the clone, the script
    # included. The loop stops at the clone folder, whose path is
    # one character shorter than $root.
    $step = $full
    while ($step.Length -ge $root.Length) {
        $item = Get-Item -LiteralPath $step -Force
        if ($item.Attributes -band [IO.FileAttributes]::ReparsePoint) {
            Refuse ("$Script passes through a link at $step; refusing " +
                'to run it.')
        }
        $step = Split-Path -Parent $step
    }

    Invoke-Native powershell.exe -NoProfile -NonInteractive `
        -ExecutionPolicy Bypass -File $full
    exit $LASTEXITCODE
} catch {
    Refuse ('the bootstrap stopped on an unexpected error: ' +
        $_.Exception.Message)
}
